INSERT INTO `quotation` (`id`, `type`, `emailAddress`, `description`, `date`)
VALUES
(NULL, 'Szita felújítás', 'teszt@teszt.hu', 'Teszt árajánlat 1', NULL),
(NULL, 'Tárcsás teherbíró eszköz', 'teszt2@teszt.hu', 'Teszt árajánlat 2', NULL),
(NULL, 'Mérőóra javítás', 'teszt3@teszt.hu', 'Teszt árajánlat 3', NULL),
(NULL, 'Nyitható CBR edények gyártása', 'teszt4@teszt.hu', 'Teszt árajánlat 4', NULL),
(NULL, 'Szita felújítás', 'teszt5@teszt.hu', 'Teszt árajánlat 5', NULL),
(NULL, 'Mérőóra javítás', 'teszt6@teszt.hu', 'Teszt árajánlat 6', NULL),
(NULL, 'Mérőóra javítás', 'teszt7@teszt.hu', 'Teszt árajánlat 7', NULL),
(NULL, 'Mérőóra javítás', 'teszt8@teszt.hu', 'Teszt árajánlat 8', NULL),
(NULL, 'Szita felújítás', 'teszt9@teszt.hu', 'Teszt árajánlat 9', NULL),
(NULL, 'Tárcsás teherbíró eszköz', 'teszt10@teszt.hu', 'Teszt árajánlat 10', NULL),
(NULL, 'Tárcsás teherbíró eszköz', 'teszt11@teszt.hu', 'Teszt árajánlat 11', NULL),
(NULL, 'Tárcsás teherbíró eszköz', 'teszt12@teszt.hu', 'Teszt árajánlat 12', NULL),
(NULL, 'Tárcsás teherbíró eszköz', 'teszt13@teszt.hu', 'Teszt árajánlat 13', NULL),
(NULL, 'Tárcsás teherbíró eszköz', 'teszt14@teszt.hu', 'Teszt árajánlat 14', NULL),
(NULL, 'Tárcsás teherbíró eszköz', 'teszt15@teszt.hu', 'Teszt árajánlat 15', NULL),
(NULL, 'Szita felújítás', 'teszt16@teszt.hu', 'Teszt árajánlat 16', NULL),
(NULL, 'Szita felújítás', 'teszt17@teszt.hu', 'Teszt árajánlat 17', NULL),
(NULL, 'Szita felújítás', 'teszt18@teszt.hu', 'Teszt árajánlat 18', NULL),
(NULL, 'Mérőóra javítás', 'teszt19@teszt.hu', 'Teszt árajánlat 19', NULL),
(NULL, 'Mérőóra javítás', 'teszt20@teszt.hu', 'Teszt árajánlat 20', NULL),
(NULL, 'Szita felújítás', 'teszt21@teszt.hu', 'Teszt árajánlat 21', NULL),
(NULL, 'Szita felújítás', 'teszt22@teszt.hu', 'Teszt árajánlat 22', NULL);